package Utilities;

public class TradeFinance_Locators {
    public String tradefinance_item = "//a[@alt=\"Trade Finance\"]/descendant::span[@class=\"oj-navigationlist-item-label\"]";
    public String LC_item = "//a[@alt=\"Letter Of Credit / Contract\"]/descendant::span[@class=\"oj-navigationlist-item-label\"]";
    public String import_LC = "//a[@alt=\"Import Letter of Credit / Contract\"]/descendant::span[@class=\"oj-navigationlist-item-label\"]";
    public String Initiate_LC = "//a[@alt=\"Initiate Letter of Credit / Contract\"]/descendant::span[@class=\"oj-navigationlist-item-label\"]";
    public String create_LC = "//oj-button[@id=\"createButton\"]/descendant::span[@class=\"oj-button-text\"]";
    //Create LC - LC/Contract Details Tab
    public String Applicant_Account_forCharges = "//oj-select-one[@value=\"{{account}}\"]/descendant::span[@class=\"oj-select-chosen\"]";
    public String Applicant_Acc_searched_item = "//*[@id=\"oj-listbox-result-label-3\"]";
    public String Applicant_Acc_Select_Branch = "//*[@id=\"oj-select-choice-9\"]/a";
    public String Applicant_Acc_Select_Branch_item = "oj-listbox-results-9";
    public String Applicant_Div = "//*[@id=\"oj-select-choice-Applicant5739740\"]";
    public String Applicant_item = "//*[@id=\"oj-listbox-results-Applicant5739740\"]";
    public String Applicant_Address1 = "//div[@class=\"oj-text-field-middle\"]/descendant::*[@id=\"applicantAddressline1|input\"]";
    public String Applicant_Address2 = "//div[@class=\"oj-text-field-middle\"]/descendant::*[@id=\"applicantAddressline2|input\"]";
    public String Applicant_Address3 = "//div[@class=\"oj-text-field-middle\"]/descendant::*[@id=\"applicantAddressline3|input\"]";
    public String Country_Lov = "//*[@id=\"ojChoiceId_applicantCountry_selected\"]";
    public String Country_Searched_Item = "//*[@id=\"oj-listbox-drop\"]";
    public String Product_type = "//*[@id=\"SelectProduct485507|input\"]";
    public String selected_product_click = "//*[@id=\"oj-listbox-results-SelectProduct485507\"]";
    public String Expiry_date = "//*[@id=\"DateofExpiry6957413|input\"]";
    public String place_of_expiry = "PlaceofExpiry2128724|input";
    public String beneName = "//div[@class=\"oj-text-field-middle\"]/descendant::*[@id=\"BeneficiaryName6090582|input\"]";
    public String bene_Address1 = "//*[@id=\"Address296078|input\"]";
    public String bene_Address2 = "//*[@id=\"AddressLine25059124|input\"]";
    public String bene_Address3 = "//*[@id=\"AddressLine32484206|input\"]";
    public String bene_Country_Lov = "//*[@id=\"oj-select-choice-Country7808846\"]";
    public String bene_Country_Searched_Item = "//*[@id=\"oj-listbox-drop\"]";
    public String CA_bankAddress_details = "//*[@id=\"BankDetails3929745|input\"]";
    public String Next_Button = "//*[@id=\"tracker\"]/div/div/div/div[3]/div/div[2]/oj-button[1]/button/div";
    public String partialShipment_1 = "//*[@id=\"oj-select-choice-PartialShipment54\"]";
    public String partialShipment_4 = "//*[@id=\"oj-listbox-drop\"]";
    public String CreditAvailedBy_Box = "//*[@id=\"oj-select-choice-CreditAvailableBy4671901\"]";
    public String CreditAvailedBy_list = "//*[@id=\"oj-listbox-drop\"]";
    public String Bene_Detail_Existing_button = "//*[@id=\"BeneficiaryDetails4922917\"]/div/span[1]";
    public String Bene_Detail_Existing_BeneName = "//*[@id=\"oj-select-choice-BeneficiaryName4609236\"]";
    public String Bene_Detail_Existing_BeneLov = "//*[@id=\"oj-listbox-drop\"]";
    public String Airport_of_Departure = "//*[@id=\"PortofLoading17|input\"]";
    public String Trans_shipment_Box= "//*[@id=\"oj-select-choice-Transshipment74\"]";
    public String Trans_shipment_Lov= "//*[@id=\"oj-listbox-drop\"]";
    public String Dispatch_from= "//*[@id=\"PlaceofTaking21|input\"]";
    public String Airport_of_Destination= "//*[@id=\"PortofDischarge7|input\"]";
    public String For_Transpotation= "//*[@id=\"PlaceofFinalDestination90|input\"]";
    public String shipment_Date= "//*[@id=\"ShipmentDate14|input\"]";
    public String Country_Origin= "//*[@id=\"oj-select-choice-countryOfOrigin\"]";
    public String Country_Origin_Lov= "//*[@id=\"oj-listbox-drop\"]";
    public String Next_Button_Second_tab = "//*[@id=\"tracker\"]/div/div/div/div[3]/div/div[2]/oj-button[1]/button/div";
    public String Goods_description= "//*[@id=\"45A|input\"]";
    public String Documents_description= "//*[@id=\"46A|input\"]";
    public String Additional_Conditions= "//*[@id=\"47A|input\"]";
    public String Documents_Submit_date= "//*[@id=\"InputDays2748051|input\"]";
    public String IncoTerms_Box= "//*[@id=\"oj-select-choice-Incoterms7672858\"]";
    public String IncoTerms_Lov= "//*[@id=\"oj-listbox-drop\"]";
    public String Next_Button_Third_tab= "//*[@id=\"tracker\"]/div/div/div/div[3]/div/div[2]/oj-button[1]/button/div";
    public String Advising_Bank_Swift= "//*[@id=\"advBankSwiftCode|input\"]";
    public String Advising_Bank_Swift_Verify= "//*[@id=\"tracker\"]/div/div/page-section/obdxcomponent/div/div/div[2]/div/oj-form-layout/div/div[1]/div[2]/div/div[2]/div[2]/oj-button/button/div";
    public String Advising_Bank_NameAdd_Button= "//*[@id=\"ui-id-426|rb\"]";
    public String SpecialPay_For_Bene= "//*[@id=\"SpecialPaymentConditionsforBeneficiary75|input\"]";
    public String SpecialPay_For_Bank= "//*[@id=\"SpecialPaymentConditionsforBankOnly84|input\"]";
    public String Confirmation_Instruction_Confirm_btn= "//*[@id=\"ConfirmationInstructions83\"]/div/span[1]";
    public String Confirmation_Instruction_MayConfirm_btn= "//*[@id=\"ConfirmationInstructions83\"]/div/span[2]";
    public String Confirmation_Instruction_Without_btn= "//*[@id=\"ConfirmationInstructions83\"]/div/span[3]";
    public String Confirmation_Instruction_Request_Confirmation_Box= "//*[@id=\"oj-select-choice-RequestedConfirmationParty50\"]";
    public String Confirmation_Instruction_Request_Confirmation_Lov= "//*[@id=\"oj-listbox-drop\"]";
    public String Sender_to_receiver_Info= "//*[@id=\"SendertoReceiverInformation99|input\"]";
    public String Charges= "//*[@id=\"Charges6|input\"]";
    public String Next_Button_Fourth_tab= "//*[@id=\"tracker\"]/div/div/div/div[3]/div/div[2]/oj-button[1]/button/div";
    public String Term_Condition= "//*[@id=\"AcceptTermsandConditions100\"]/div/span";
    public String Submit= "//*[@id=\"tracker\"]/div/div/div/div[3]/div/div[2]/oj-button[1]/button/div";
    public String Review_Screen_Submit= "//*[@id=\"tracker\"]/div/div/page-section/obdxcomponent/div/div/div/div/oj-form-layout/div/div[12]/div[2]/div/oj-button[1]/button/div";

}
